const INVALID_ID = 400;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const MONGODB_DUPLICATE_ERROR = 409;
const UNAUTHORIZED = 401;

module.exports = {
  INVALID_ID,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  MONGODB_DUPLICATE_ERROR,
  UNAUTHORIZED,
}